# Site settings
title: Kbeznak Parmatonic
author: Kishan Sheshagiri
email: kishan.sheshagiri@gmail.com
description: >
  Welcome to Kbeznak Parmatonic, the flagship product of Texas A&M University System.
  We hope to create a better user experience by applying design metrics.
baseurl: ""
url: "https://http://kanzebk.github.io/"
twitter_username: kishanhulkodu
github_username:  kishansheshagiri

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag

